# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title     : Linear Multistep Methods
author    : Zhihua Ma
copyright : "2023--2025"  # Copyright year to be placed in the footer
logo      : images/logo2c.svg
last-updated: "2023"
only_build_toc_files: true  


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: odebook.tex

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/zhihuammu/ODE-book  # Online location of your book
#  path_to_book: docs # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon               : images/favicon.png  # A path to a favicon image
  home_page_in_navbar   : false
  use_multitoc_numbering: false      
  use_repository_button : false
  use_edit_page_button  : false
  use_issues_button     : false
  use_download_button   : true
  use_source_button     : false
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>
  # comments:
    # hypothesis          : false
#  announcement: "My announcement!"
  
sphinx:
  config:
# bibtex_reference_style: author_year    
    html_show_copyright: true
    language: en          
    latex_elements:
        preamble: |
          \newcommand{\N}{\mathbb{N}}
          \newcommand{\Z}{\mathbb{Z}}
          \newcommand{\R}{\mathbb{R}}
          \newcommand{\C}{\mathbb{C}}
          \newcommand{\D}{\mathrm{D}}
          \newcommand{\E}{\mathrm{E}}
          \newcommand{\S}{\mathrm{S}}          
          \newcommand{\dy}{\mathrm{d}y}
          \newcommand{\dx}{\mathrm{d}x}
          \newcommand{\ds}{\mathrm{d}s}
          \newcommand{\dt}{\mathrm{d}t}                                        
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      tex:
        macros:
          "N": "\\mathbb{N}"
          "Z": "\\mathbb{Z}"
          "R": "\\mathbb{R}"
          "C": "\\mathbb{C}"
          "D": "\\mathrm{D}"
          "E": "\\mathrm{E}"
          "S": "\\mathrm{S}"          
          "dy": "\\mathrm{d}y"
          "dx": "\\mathrm{d}x"
          "ds": "\\mathrm{d}s"
          "dt": "\\mathrm{d}t"
    hide_solutions: false
#    html_extra_path: exSol
    # html_theme: sphinx_material
    html_theme: sphinx_book_theme
  #  html_theme: pydata_sphinx_theme
    html_theme_options:    
      # footer_start  : copyright
      # footer_center : 
      # footer_end    : theme-version    
      primary_sidebar_end   : 
        - indices
        - sphinx-version        
  extra_extensions:
    - sphinx_proof
    - sphinx_exercise    
    - sphinxcontrib.tikz
    # - sphinx_togglebutton      
    - sphinx_inline_tabs    

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    - html_admonition
    - fieldlist   
    - deflist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context    
  